services:
  api:
    build:
      dockerfile: ./cmd/api/Dockerfile
      context: .
    develop:
      watch:
        - action: rebuild
          path: ./cmd/api/
        - action: rebuild
          path: ./internal/
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3001:3001"
    tty: true
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tesseral"
    expose:
      - 5432
    ports:
      - "5433:5432"  # Use a different port to avoid conflict with your local Postgres
    healthcheck:
      test:
        ["CMD-SHELL", "PGPASSWORD=password pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./.local/postgres-docker:/var/lib/postgresql/data
      - ./.local/tmp:/tmp/local
  console:
    command: bash -c "npm i --force && npm run dev"
    env_file:
      - .env
    expose:
      - 3000
    image: node:22.11.0
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./console:/console:cached
    working_dir: /console
  kms:
    environment:
      KMS_REGION: ${AWS_DEFAULT_REGION}
      PORT: 4566
    expose:
      - 4566
    image: nsmithuk/local-kms:latest
    ports:
      - 4566:4566
      - 4599:4566
    volumes:
      - ./.local/kms/data/:/data/
      - ./.local/kms/seed.yaml:/init/seed.yaml
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./.local/nginx:/etc/nginx/conf.d
  s3:
    image: adobe/s3mock:latest
    environment:
      - initialBuckets=tesseral-user-content
      - root=containers3root
      - retainFilesOnExit=true
    ports:
      - 9090:9090
    volumes:
      - ./.local/s3:/containers3root
  ses:
    build:
      dockerfile: ./.local/ses/Dockerfile
      context: .
    environment:
      AWS_SES_ACCOUNT: ${AWS_SES_ACCOUNT}
      SMTP_TRANSPORT: ${SMTP_TRANSPORT}
    working_dir: /srv/www/dist
    ports:
      - 8005:8005
    volumes:
      - ./.local/ses/output:/output
  vault-ui:
    command: bash -c "npm i --force && npm run dev"
    environment:
      UI_BUILD_IS_DEV: 1
    expose:
      - 3002
    image: node:22.11.0
    ports:
      - "3002:3002"
    tty: true
    volumes:
      - ./vault-ui:/vault-ui:cached
    working_dir: /vault-ui
  smtp:
    image: maildev/maildev
    expose:
      - 1025
    ports:
      - "1080:1080"

  # svix
  svix:
    image: svix/svix-server
    environment:
      WAIT_FOR: "true"  # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      SVIX_DB_DSN: "postgresql://postgres:password@svix_postgres/svix"
      SVIX_JWT_SECRET: "d883js80osdfjshk2332423adsfahj3x"
      SVIX_WHITELIST_SUBNETS: "[172.0.0.0/8]"
    expose:
      - 8071
    ports:
      - "8071:8071"
    depends_on:
    - svix_postgres
    - redis
  svix_ui:
    image: aeolun/svix-ui
    env_file:
      - .env
    ports:
      - "4700:80"

  svix_postgres:
    image: postgres:15.8
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "svix"
    expose:
      - 5432
    ports:
      - "5434:5432"  # Use a different port to avoid conflict with your local Postgres
    healthcheck:
      test:
        ["CMD-SHELL", "PGPASSWORD=password pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./.local/svix-postgres-docker:/var/lib/postgresql/data
      - ./.local/tmp:/tmp/local
  redis:
    image: "docker.io/redis:7-alpine"
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    volumes:
      - "redis-data:/data"
  webhook-tester:
    image: tarampampam/webhook-tester
    expose:
      - 8080

volumes:
  redis-data:
